name: Generate GitHub Stats (premium)

on:
  schedule:
    - cron: '0 3 * * *'   # 03:00 UTC diariamente
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run generator
        env:
          GITHUB_USER: Domisnnet
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python generate_stats.py

      - name: Commit generated assets
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add assets/github-stats.png assets/github-stats.svg || true
          git commit -m "chore(stats): update github-stats artifacts" || echo "No changes to commit"
          git push